rvm:
  - 2.2
  - 2.3
  - 2.4.4
  - 2.5.1
notifications:
  webhooks:
    - https://webhook.commit-email.info/
gemfile:
  - gemfiles/capybara2.gemfile
  - gemfiles/capybara3.gemfile
before_install:
  - gem update bundler
